module top_module (
    // 33MHz clock should be generated by PLL
    input clk_33,
    input nrst,

/* verilator lint_off UNUSED */
    // RGB bus
    input [23:0] rgb,
    input hsync, vsync, rgb_clk,
/* verilator lint_on UNUSED */

    // Driver output
    output sclk,
    output gclk,
    output lat,
    output [29:0] sin,
    output driver_ready,
    output column_ready,
    output [4:0] sout_mux,

    // Driver input
    input sout,
    input position_sync,

    //Columns multiplexers
    output [7:0] mux_out,

/* verilator lint_off UNUSED */
    // Encoder
    input enc0, enc1
/* verilator lint_on UNUSED */
);

/*
 * Interconnect signals
 */
logic [29:0] framebuffer_dat;
logic        framebuffer_sync;

logic clk_lse;

/*
 * Temporary zone where interconnect logics are driven while unused
 */
assign framebuffer_dat = 30'h0;
assign framebuffer_sync = 1'b0;
assign clk_lse = 1'b0;
assign mux_out = 8'h00;

/*
 * Default configuration for drivers
 * To change the default configuration, please go to drivers_conf.sv
 */
`include "drivers_conf.sv"

// Driver output
driver_controller #(.BLANKING_TIME(80)) main_driver_controller (
    .clk_hse(clk_33),
    .clk_lse(clk_lse),
    .nrst(nrst),
    .framebuffer_dat(framebuffer_dat),
    .position_sync(position_sync),
    .driver_sclk(sclk),
    .driver_gclk(gclk),
    .driver_lat(lat),
    .drivers_sin(sin),
    .driver_sout(sout),
    .driver_sout_mux(sout_mux),
    .serialized_conf(serialized_conf),
    .driver_ready(driver_ready),
    .column_ready(column_ready)
);

endmodule
