image: tuetuopay/verilator

stages:
  - lint
  - build
  - test
  - host
  - bundle

variables:
  SBC_DIR: "SBC"
  RENDERER_POC_DIR: "tools/renderer"
  FPGA_DIR: "FPGA"
  LIBSPIROSE_DIR: "SBC/libSpiROSE"

before_script:
  - git submodule init
  - git submodule update

lint_lower_tower:
  stage: lint
  script:
    - cd LCD_Display
    - make lint

build_lower_tower:
  image: tuetuopay/arm-none-eabi
  stage: build
  script:
    - cd LCD_Display
    - make

test_lower_tower:
  image: tuetuopay/arm-none-eabi
  stage: test
  script:
    - cd LCD_Display
    - make test

host_lower_tower:
  image: tuetuopay/arm-none-eabi
  stage: host
  script:
    - cd LCD_Display
    - make host

lint_sbc:
  stage: lint
  script:
    - cd $SBC_DIR
    - make lint

build_sbc:
  stage: build
  script:
    - cd $SBC_DIR
    - make build

test_sbc:
  stage: test
  script:
    - cd $SBC_DIR
    - make test

host_sbc:
   stage: host
   script:
   - cd $SBC_DIR
   - make host

lint_renderer-poc:
  stage: lint
  image: tuetuopay/clang
  script:
    - cd $RENDERER_POC_DIR
    - make lint

build_renderer-poc:
  stage: build
  image: tuetuopay/glfw
  script:
    - cd $RENDERER_POC_DIR
    - make build
    - make test
  except:
    - master

host_renderer-poc:
  stage: host
  image: tuetuopay/glfw
  script:
    - cd $RENDERER_POC_DIR
    - make host

bundle_renderer-poc:
  stage: bundle
  image: tuetuopay/glfw
  script:
    - cd $RENDERER_POC_DIR
    - make bundle
  artifacts:
    paths:
      - $RENDERER_POC_DIR/renderer-poc.tar.gz
    expire_in: 1 week
  only:
    - master

lint_fpga:
  stage: lint
  image: tuetuopay/verilator
  script:
    - cd $FPGA_DIR
    - make lint

build_fpga:
  stage: build
  image: tuetuopay/verilator
  script:
    - cd $FPGA_DIR
    - make build

test_fpga:
  stage: test
  image: tuetuopay/verilator
  script:
    - cd $FPGA_DIR
    - make test

host_fpga:
  stage: host
  image: tuetuopay/verilator
  script:
    - cd $FPGA_DIR
    - make host

lint_libspirose:
  stage: lint
  image: tuetuopay/clang
  script:
    - cd $LIBSPIROSE_DIR
    - make lint
build_libspirose:
  stage: build
  image: tuetuopay/glfw
  script:
    - cd $LIBSPIROSE_DIR
    - make build
test_libspirose:
  stage: test
  image: tuetuopay/glfw
  script:
    - cd $LIBSPIROSE_DIR
    - make lint
host_libspirose:
  stage: host
  image: tuetuopay/glfw
  script:
    - cd $LIBSPIROSE_DIR
    - make host
bundle_libspirose:
  stage: bundle
  image: tuetuopay/glfw
  script:
    - cd $LIBSPIROSE_DIR
    - make bundle
  artifacts:
    paths:
      - $LIBSPIROSE_DIR/libSpiROSE.tar.gz
    expire_in: 1 week
  only:
    - master
