image: tuetuopay/verilator

stages:
  - lint
  - build
  - test
  - host
  - bundle

variables:
  JOBS: 2
  RENDERER_POC_DIR: "tools/renderer"
  FPGA_DIR: "FPGA"
  LIBSPIROSE_DIR: "SBC/libSpiROSE"

before_script:
  - git submodule init
  - git submodule update

lower_tower/lint:
  stage: lint
  script:
    - cd LCD_Display
    - make lint

lower_tower/build:
  image: tuetuopay/arm-none-eabi
  stage: build
  script:
    - cd LCD_Display
    - make

lower_tower/test:
  image: tuetuopay/arm-none-eabi
  stage: test
  script:
    - cd LCD_Display
    - make test

lower_tower/host:
  image: tuetuopay/arm-none-eabi
  stage: host
  script:
    - cd LCD_Display
    - make host

renderer-poc/lint:
  stage: lint
  image: tuetuopay/clang
  script:
    - cd $RENDERER_POC_DIR
    - make lint

renderer-poc/build:
  stage: build
  image: tuetuopay/glfw
  script:
    - cd $RENDERER_POC_DIR
    - make build
    - make test

renderer-poc/host:
  stage: host
  image: tuetuopay/glfw
  script:
    - cd $RENDERER_POC_DIR
    - make host

renderer-poc/bundle:
  stage: bundle
  image: tuetuopay/glfw
  script:
    - cd $RENDERER_POC_DIR
    - make bundle
  artifacts:
    paths:
      - $RENDERER_POC_DIR/renderer-poc.tar.gz
    expire_in: 1 week
  only:
    - master

fpga/lint:
  stage: lint
  image: tuetuopay/verilator
  script:
    - cd $FPGA_DIR
    - make lint

fpga/build:
  stage: build
  image: tuetuopay/verilator
  script:
    - cd $FPGA_DIR
    - make build
    - make test

fpga/host:
  stage: host
  image: tuetuopay/verilator
  script:
    - cd $FPGA_DIR
    - make host

libspirose/lint:
  stage: lint
  image: tuetuopay/clang
  script:
    - cd $LIBSPIROSE_DIR
    - make lint
libspirose/build:
  stage: build
  image: tuetuopay/glfw
  script:
    - cd $LIBSPIROSE_DIR
    - make build -j$(JOBS)
libspirose/test:
  stage: test
  image: tuetuopay/glfw
  script:
    - cd $LIBSPIROSE_DIR
    - echo Testing desktop OpenGL
    - make build -j$(JOBS)
    - make install
    - make test -j$(JOBS)
    - echo Testing OpenGL ES
    - make clean
    - make build UNAME_P=armv7l -j$(JOBS)
    - make install
    - make test -j$(JOBS)
libspirose/host:
  stage: host
  image: tuetuopay/glfw
  script:
    - cd $LIBSPIROSE_DIR
    - make host
libspirose/bundle:
  stage: bundle
  image: tuetuopay/glfw
  script:
    - cd $LIBSPIROSE_DIR
    - make bundle -j$(BUNDLE)
  artifacts:
    paths:
      - $LIBSPIROSE_DIR/libSpiROSE.tar.gz
    expire_in: 1 week
  only:
    - master
