image: tuetuopay/arm-none-eabi
stages:
  - lint
  - build
  - test
  - host

before_script:
    - git submodule init
    - git submodule update

lint_lower_tower:
  stage: lint
  image: rfc1149/rose-dev
  script:
    - cd LCD_Display
    - make lint

build_lower_tower:
  stage: build
  script:
    - cd LCD_Display
    - make

test_lower_tower:
  stage: test
  script:
    - cd LCD_Display
    - make test

host_lower_tower:
  stage: host
  script:
    - cd LCD_Display
    - make host
